name: Changelog Workflow - Add tag, create a github release and update changelog.md

on:
  push:
    branches:
      - "release/**"
  workflow_dispatch:

jobs:
  tag_release_changelog:
    name: Tag, Release and Changelog
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
      # Extract version name
      - name: Extract Version
        shell: bash
        run: |
          echo "##[set-output name=version_name;]$(echo ${GITHUB_REF#refs/heads/release/})"
          echo "##[set-output name=tag_name;]$(echo v${GITHUB_REF#refs/heads/release/})"
          echo Setting up release v${GITHUB_REF#refs/heads/release/}
        id: extract_version
      # Create Tag
      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{steps.extract_version.outputs.tag_name}}',
              sha: context.sha
            })
      # Build Changelog
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          commitMode: false
          toTag: ${{steps.extract_version.outputs.tag_name}}
          configuration: ".github/config/changelog_pullrequest.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Create Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
          tag_name: ${{steps.extract_version.outputs.tag_name}}
      # Update changelog file
      - name: Update CHANGELOG.md
        run: |
          echo "## [${{steps.extract_version.outputs.version_name}}] - `date +%d-%m-%Y`" >> CHANGELOG.md.tmp
          echo "${{steps.build_changelog.outputs.changelog}}" >> CHANGELOG.md.tmp
          echo '-n' >> CHANGELOG.md
          cat CHANGELOG.md >> CHANGELOG.md.tmp
          mv CHANGELOG.md.tmp CHANGELOG.md
      # Push changelog file
      - name: Commit updated CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
