name: Internal Workflow - Uploads QA build

on:
  push:
    branches:
      - 'master' #'internal**'

jobs:

  config:
    name: Load dotenv config
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      dotenv: ${{ steps.dotenv.outputs }}
    steps:
      # Load dotenv config
      - name: Load dotenv config
        uses: falti/dotenv-action@v0.2.4
        id: dotenv
        with:
          path: ./.github/workflows/.env
          log-variables: true

  internal_android:
    name: Android Internal Workflow
    needs: config
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Output dotenv config
      - name: Output dotenv flutter version
        run: "echo $FLUTTER_VERSION"
        env:
          FLUTTER_VERSION: ${{ needs.config.outputs.dotenv.FLUTTER_VERSION }}
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Install SDKs
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '$FLUTTER_VERSION'
          channel: 'stable'
        env: 
          FLUTTER_VERSION: ${{ steps.dotenv.outputs.FLUTTER_VERSION }}
      # Install SSH Key for private repository dependencies
      - name: Install GitHub SSH Key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.GIT_SSH_KEY }}
      # Get Flutter Dependencies
      - name: Get Flutter dependencies
        run: |
          flutter pub upgrade
          flutter pub get
      # Execute build_runner pub
      - name: Execute build_runner Code Generation
        run: flutter pub run build_runner build --delete-conflicting-outputs
      # Fastlane Setup
      - name: Setup Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Setup Fastlane
        run: cd android && gem install bundler && bundle install && cd ..
      # Decrypt Keystore
      - name: Decrypt Keystore
        id: keystore_file
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: 'keystore.jks'
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}
      # Upload QA build
      - name: Upload QA Build
        run: |
          flutter build apk -t lib/main_qa.dart --flavor qa --release
          cd android
          bundle exec fastlane internal_release --env qa is_flutter:true
        env:
          KEYSTORE_FILE: ${{ steps.keystore_file.outputs.filePath }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  internal_ios:
    name: iOS Internal Workflow
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      # Basic Setup
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # EXTRA: Install SSH Key for private repository dependencies
      - name: Install GitHub SSH Key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.GIT_SSH_KEY }}
      # Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '$FLUTTER_VERSION'
          channel: 'stable'
        env: 
          FLUTTER_VERSION: ${{ steps.dotenv.outputs.FLUTTER_VERSION }}
      # Fastlane Setup
      - name: Setup Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Setup Fastlane
        run: cd ios && gem install bundler && bundle install && cd ..
      # Get Flutter Dependencies
      - name: Get Flutter dependencies
        run: |
          flutter pub upgrade
          flutter pub get
      # Execute build_runner pub
      - name: Execute build_runner Code Generation
        run: flutter pub run build_runner build --delete-conflicting-outputs
      # Upload to Appstore Connect
      # - MATCH_GIT_BASIC_AUTHORIZATION: Generated with "username:token" encoded in Base64
      # - FASTLANE_USER/PASSWORD: The account uploading builds to Testflight
      # - MATCH_PASSWORD: Certificates password
      # - Using qa@levinriegner.com to upload builds to Testflight
      - name: Upload QA build
        run: |
          flutter build ios -t lib/main_qa.dart --flavor QA --release --no-codesign
          cd ios
          bundle exec fastlane testflight_release is_ci:true --env qa
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
