name: Release Workflow - Upload Production builds to Playstore & Appstore Connect

on:
  push:
    branches:
      - 'release**'

env:
  # Self-hosted OS (needed to install Ruby)
  ImageOS: macos1015

jobs:
  # Config Job
  config:
    name: Load dotenv Config
    # WAS: ubuntu-latest
    runs-on: self-hosted
    timeout-minutes: 5
    outputs:
      # dotenv variables
      FLUTTER_VERSION: ${{ steps.dotenv.outputs.FLUTTER_VERSION }}
      ANDROID_SUPPORTED: ${{ steps.dotenv.outputs.ANDROID_SUPPORTED }}
      IOS_SUPPORTED: ${{ steps.dotenv.outputs.IOS_SUPPORTED }}
      RUBY_VERSION: ${{ steps.dotenv.outputs.RUBY_VERSION }}
      JAVA_VERSION: ${{ steps.dotenv.outputs.JAVA_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Load dotenv config
      - name: Load dotenv config
        uses: falti/dotenv-action@v0.2.5
        id: dotenv
        with:
          path: ./.github/workflows/.env
          log-variables: true
  # Android Job
  release_android:
    name: Android Release Workflow
    needs: config
    if: needs.config.outputs.ANDROID_SUPPORTED == 'true'
    # WAS: ubuntu-latest
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # SSH Key for private repository dependencies
      - name: Install GitHub SSH Key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GIT_SSH_KEY }}
      # Install SDKs
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ needs.config.outputs.FLUTTER_VERSION }}
          channel: 'stable'
      # Flutter project build
      - name: Get Flutter dependencies
        run: |
          flutter pub upgrade
          flutter pub get
      - name: Execute build_runner Code Generation
        run: flutter pub run build_runner build --delete-conflicting-outputs
      # Fastlane Setup
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ needs.config.outputs.RUBY_VERSION }}
      - name: Setup Fastlane
        run: cd android && gem install bundler && bundle install && cd ..
      # Decrypt Keystore
      - name: Decrypt Keystore
        id: keystore_file
        uses: timheuer/base64-to-file@v1.0.4
        with:
          fileName: 'keystore.jks'
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}
      # Decrypt Play Store Json Key
      - name: Decrypt JSON Key
        id: json_key_file
        uses: timheuer/base64-to-file@v1.0.4
        with:
          fileName: 'json_key.json'
          encodedString: ${{ secrets.GOOGLE_PLAY_JSON_KEY_BASE64 }}
      # Upload Production build
      - name: Upload Production Build
        run: |
          flutter build appbundle -t lib/main_prod.dart --flavor production --release
          cd android
          bundle exec fastlane playstore_release --env production is_flutter:true json_key:$JSON_KEY_FILE
        env:
          KEYSTORE_FILE: ${{ steps.keystore_file.outputs.filePath }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          JSON_KEY_FILE: ${{ steps.json_key_file.outputs.filePath }}
  # iOS Job
  release_ios:
    name: iOS Release Workflow
    needs: config
    if: needs.config.outputs.IOS_SUPPORTED == 'true'
    # WAS: macos-latest
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # SSH Key for private repository dependencies
      - name: Install GitHub SSH Key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GIT_SSH_KEY }}
      # Install SDKs
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ needs.config.outputs.FLUTTER_VERSION }}
          channel: 'stable'
      # Flutter Project build
      - name: Get Flutter dependencies
        run: |
          flutter pub upgrade
          flutter pub get
      - name: Execute build_runner Code Generation
        run: flutter pub run build_runner build --delete-conflicting-outputs
      # Fastlane Setup
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ needs.config.outputs.RUBY_VERSION }}
      - name: Setup Fastlane
        run: cd ios && gem install bundler && bundle install && cd ..
      # Upload to Appstore Connect
      - name: Upload Production build
        run: |
          flutter build ios -t lib/main_prod.dart --flavor Production --release --no-codesign
          cd ios
          bundle exec fastlane testflight_release is_ci:true --env production
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
