name: Run Flutter Unit Tests

on:
  push:
    branches:
      - '**'
      - '!internal**'
      - '!release**'
      - '!file-sync**'
  workflow_dispatch:

jobs:
  # Config Job
  config:
    name: Load dotenv Config
    # WAS: ubuntu-latest
    runs-on: self-hosted
    timeout-minutes: 5
    outputs:
      # dotenv variables
      FLUTTER_VERSION: ${{ steps.dotenv.outputs.FLUTTER_VERSION }}
      ANDROID_SUPPORTED: ${{ steps.dotenv.outputs.ANDROID_SUPPORTED }}
      IOS_SUPPORTED: ${{ steps.dotenv.outputs.IOS_SUPPORTED }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Load dotenv config
      - name: Load dotenv config
        uses: falti/dotenv-action@v0.2.5
        id: dotenv
        with:
          path: ./.github/workflows/.env
          log-variables: true
  test:
    # WAS: ubuntu-latest
    runs-on: self-hosted
    needs: config
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # SSH Key for private repository dependencies
      - name: Install GitHub SSH Key
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.GIT_SSH_KEY }}
      # Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ needs.config.outputs.FLUTTER_VERSION }}
          channel: 'stable'
      # Flutter project build
      - name: Get Flutter dependencies
        run: |
          flutter pub upgrade
          flutter pub get
      - name: Execute build_runner Code Generation
        run: flutter pub run build_runner build --delete-conflicting-outputs
      # Run Unit Tests
      - name: Run Unit Tests
        run: flutter test
