name: Workflow Sync

on:
  push:
    branches:
      - master
env:
  # Repositories to Sync
  REPOSITORIES: |
    levin-riegner/candid-flutter
    levin-riegner/avenew-flutter
    levin-riegner/spireworks-ios
    levin-riegner/ars-gratia-flutter
    levin-riegner/lodge-flutter
  # Files to Sync
  WORKFLOW_FILES: |
    internal.workflow.yml
    release.workflow.yml
    test.workflow.yml
  # Run the Sync Action without pushing to repos
  DRY_RUN: false
  # Commit files via Pull Request
  PULL_REQUEST: true
  AUTO_CREATE_NEW_BRANCH: true

jobs:
  github_workflow_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Running Workflow Sync
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          PULL_REQUEST: ${{ env.PULL_REQUEST}}
          AUTO_CREATE_NEW_BRANCH: ${{ env.AUTO_CREATE_NEW_BRANCH }}
