name: Changelog Workflow - Add tag, create a github release and update changelog.md

on:
  push:
    branches:
      - "release/**"
  workflow_dispatch:

jobs:
  # Config Job
  config:
    name: Load dotenv Config
    runs-on: self-hosted # WAS: ubuntu-latest
    timeout-minutes: 5
    outputs:
      # dotenv variables
      CHANGELOG_USE_PULL_REQUEST: ${{ steps.dotenv.outputs.CHANGELOG_USE_PULL_REQUEST }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Load dotenv config
      - name: Load dotenv config
        uses: falti/dotenv-action@v0.2.8
        id: dotenv
        with:
          path: ./.github/workflows/.env
          log-variables: true
  # Tag, Release and Changelog Job
  tag_release_changelog:
    name: Tag, Release and Changelog
    needs: config
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      # Extract version name
      - name: Extract Version
        shell: bash
        run: |
          echo "##[set-output name=version_name;]$(echo ${GITHUB_REF#refs/heads/release/})"
          echo "##[set-output name=tag_name;]$(echo v${GITHUB_REF#refs/heads/release/})"
          echo Setting up release v${GITHUB_REF#refs/heads/release/}
        id: extract_version
      # Create Tag
      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{steps.extract_version.outputs.tag_name}}',
              sha: context.sha
            })
      # Build Changelog
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          commitMode: false
          toTag: ${{steps.extract_version.outputs.tag_name}}
          configuration: ".github/config/changelog_pullrequest.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Create Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
          tag_name: ${{steps.extract_version.outputs.tag_name}}
      # Update changelog file
      - name: Update CHANGELOG.md
        run: |
          echo "## [${{steps.extract_version.outputs.version_name}}] - `date +%d-%m-%Y`" >> CHANGELOG.md.tmp
          echo "${{steps.build_changelog.outputs.changelog}}" >> CHANGELOG.md.tmp
          echo '-n' >> CHANGELOG.md
          cat CHANGELOG.md >> CHANGELOG.md.tmp
          mv CHANGELOG.md.tmp CHANGELOG.md
      # Push changelog: via pull request
      - if: needs.config.outputs.CHANGELOG_USE_PULL_REQUEST == 'true'
        name: Pull Request updated CHANGELOG.md
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "docs: update CHANGELOG"
          title: Update CHANGELOG for ${{steps.extract_version.outputs.tag_name}}
          branch: update-changelog
          delete-branch: true
          base: master
          labels: |
            changelog
          body: |
            Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.

            ${{steps.build_changelog.outputs.changelog}}
      # Push changelog: via master push
      - if: needs.config.outputs.CHANGELOG_USE_PULL_REQUEST != 'true'
        name: Commit updated CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
